version: '3'
services:
  frontend:
    image: frontend-app
    build:
      context: ./frontend/my-react-app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: backend-app
    build:
      context: ./backend
    ports:
      - "5000:5000"
